In [9]:
# Experiments imports
from ternary_weight_mlp import *
import mlflow

In [25]:
# HYPERPARAMETERS
LEARNING_RATE  = 0.2  # Starting learning rate
EPOCHS = 30000
X_train, y_train, X_test, y_test = create_torch_XOR_dataset()

model_XOR = TwoLayerMLP()

 # define the loss
loss_function = torch.nn.BCELoss()
optimizer = torch.optim.SGD(model_XOR.parameters(), lr=LEARNING_RATE)


train(model_XOR, loss_function, optimizer, X_train, y_train, EPOCHS)

0.7153326869010925
0.693189263343811
0.6922516822814941
0.6921882033348083
0.6921530365943909
0.6921180486679077
0.6920823454856873
0.6920456886291504
0.6920081973075867
0.6919697523117065
0.69193035364151
0.6918898224830627
0.6918483376502991
0.6918057203292847
0.6917619109153748
0.6917168498039246
0.6916705369949341
0.6916228532791138
0.6915738582611084
0.6915232539176941
0.6914712190628052
0.6914175152778625
0.6913622617721558
0.6913051009178162
0.6912462115287781
0.6911852955818176
0.6911224126815796
0.691057562828064
0.6909902691841125
0.6909208297729492
0.6908487677574158
0.6907744407653809
0.690697193145752
0.6906173825263977
0.6905344724655151
0.6904485821723938
0.690359354019165
0.6902668476104736
0.6901708245277405
0.6900709271430969
0.689967155456543
0.6898593306541443
0.689747154712677
0.689630389213562
0.689508855342865
0.6893821954727173
0.6892503499984741
0.6891129612922668
0.688969612121582
0.6888202428817749
0.6886643171310425
0.6885014772415161
0.6883316040039062
0.68

[0.7153326869010925,
 0.693189263343811,
 0.6922516822814941,
 0.6921882033348083,
 0.6921530365943909,
 0.6921180486679077,
 0.6920823454856873,
 0.6920456886291504,
 0.6920081973075867,
 0.6919697523117065,
 0.69193035364151,
 0.6918898224830627,
 0.6918483376502991,
 0.6918057203292847,
 0.6917619109153748,
 0.6917168498039246,
 0.6916705369949341,
 0.6916228532791138,
 0.6915738582611084,
 0.6915232539176941,
 0.6914712190628052,
 0.6914175152778625,
 0.6913622617721558,
 0.6913051009178162,
 0.6912462115287781,
 0.6911852955818176,
 0.6911224126815796,
 0.691057562828064,
 0.6909902691841125,
 0.6909208297729492,
 0.6908487677574158,
 0.6907744407653809,
 0.690697193145752,
 0.6906173825263977,
 0.6905344724655151,
 0.6904485821723938,
 0.690359354019165,
 0.6902668476104736,
 0.6901708245277405,
 0.6900709271430969,
 0.689967155456543,
 0.6898593306541443,
 0.689747154712677,
 0.689630389213562,
 0.689508855342865,
 0.6893821954727173,
 0.6892503499984741,
 0.6891129612922668,
 0

In [16]:
print_network_parameters(model_XOR)

# Example input: a batch of 1 sample with 2 features
input1 = torch.tensor([[0.0, 0.0]])
input2 = torch.tensor([[0.0, 1.0]])
input3 = torch.tensor([[1.0, 0.0]])
input4 = torch.tensor([[1.0, 1.0]])
# Forward pass to get the output
output1 = model_XOR(input1)
output2 = model_XOR(input2)
output3 = model_XOR(input3)
output4 = model_XOR(input4)

print("Output0-0:", output1)
print("Output0-1:", output2)
print("Output1-0:", output3)
print("Output1-1:", output4)

layer1.weight:
tensor([[-6.0037, -6.0312],
        [-7.6345, -7.5166]])
layer1.bias:
tensor([9.2667, 3.6240])
output_layer.weight:
tensor([[ 13.9700, -14.4251]])
output_layer.bias:
tensor([-6.6364])
Output0-0: tensor([[0.0012]], grad_fn=<SigmoidBackward0>)
Output0-1: tensor([[0.9985]], grad_fn=<SigmoidBackward0>)
Output1-0: tensor([[0.9986]], grad_fn=<SigmoidBackward0>)
Output1-1: tensor([[0.0030]], grad_fn=<SigmoidBackward0>)


In [7]:
# HYPERPARAMETERS
INIITIAL_LEARNING_RATE  = 0.2  # Starting learning rate
MAXIMUM_LEARNING_RATE = 1         # Maximum learning rate
EPOCHS = 30000
ALPHA = 2
LAMBDA = 0.05
X_train, y_train, X_test, y_test = create_torch_XOR_dataset()

model_XOR = TwoLayerMLP()

 # define the loss
loss_function = torch.nn.BCELoss()
optimizer = torch.optim.SGD(model_XOR.parameters(), lr=INIITIAL_LEARNING_RATE)

all_loss = train_with_rectified_L2(model_XOR, 
                                    loss_function, 
                                    optimizer, 
                                    X_train, 
                                    y_train,
                                    no_of_epochs=EPOCHS,
                                    ALPHA=ALPHA,
                                    LAMBDA=LAMBDA,
                                    initial_lr=INIITIAL_LEARNING_RATE,
                                    max_lr=MAXIMUM_LEARNING_RATE)

0.7245436310768127
0.2
0.7187248468399048
0.20002666666666669
0.713793933391571
0.20005333333333333
0.7096187472343445
0.20008
0.7060856819152832
0.20010666666666668
0.7030972242355347
0.20013333333333336
0.7005701661109924
0.20016
0.6984336972236633
0.20018666666666668
0.6966272592544556
0.20021333333333335
0.6950998902320862
0.20024
0.6938083171844482
0.20026666666666668
0.6927156448364258
0.20029333333333335
0.6917910575866699
0.20032
0.6910082101821899
0.20034666666666667
0.6903449296951294
0.20037333333333335
0.6897827386856079
0.20040000000000002
0.6893056035041809
0.20042666666666667
0.6889004707336426
0.20045333333333334
0.6885558366775513
0.20048000000000002
0.6882625222206116
0.20050666666666667
0.6880123615264893
0.20053333333333334
0.6877987384796143
0.20056000000000002
0.6876158118247986
0.2005866666666667
0.6874589920043945
0.20061333333333334
0.6873239874839783
0.20064
0.6872076392173767
0.2006666666666667
0.6871069073677063
0.20069333333333333
0.6870193481445312
0.20072

In [8]:
print_network_parameters(model_XOR)

# Example input: a batch of 1 sample with 2 features
input1 = torch.tensor([[0.0, 0.0]])
input2 = torch.tensor([[0.0, 1.0]])
input3 = torch.tensor([[1.0, 0.0]])
input4 = torch.tensor([[1.0, 1.0]])
# Forward pass to get the output
output1 = model_XOR(input1)
output2 = model_XOR(input2)
output3 = model_XOR(input3)
output4 = model_XOR(input4)

print("Output0-0:", output1)
print("Output0-1:", output2)
print("Output1-0:", output3)
print("Output1-1:", output4)

layer1.weight:
tensor([[-15.0000, -15.0000],
        [ 10.0010,  10.0010]])
layer1.bias:
tensor([ 10.0000, -14.9990])
output_layer.weight:
tensor([[-15.0168, -15.0166]])
output_layer.bias:
tensor([9.9667])
Output0-0: tensor([[0.0064]], grad_fn=<SigmoidBackward0>)
Output0-1: tensor([[0.9999]], grad_fn=<SigmoidBackward0>)
Output1-0: tensor([[0.9999]], grad_fn=<SigmoidBackward0>)
Output1-1: tensor([[0.0070]], grad_fn=<SigmoidBackward0>)


In [11]:
# Parameters for multiple runs
runs = 100  # Number of experiments
convergence_threshold = 0.05  # Define your convergence threshold


# Initialize MLflow experiment
mlflow.set_experiment('Interpretable_XOR_Model_Multiple_Runs')

for i in range(runs):
    with mlflow.start_run():
        # Initialize data and model
        X_train, y_train, X_test, y_test = create_torch_XOR_dataset()
        model_XOR = TwoLayerMLP()
        loss_function = torch.nn.BCELoss()
        optimizer = torch.optim.SGD(model_XOR.parameters(), lr=0.2)

        # Parameters
        params = {
            "initial_learning_rate": 0.2,
            "maximum_learning_rate": 1,
            "epochs": 30000,
            "alpha": 2,
            "lambda": 0.05
        }
        mlflow.log_params(params)

        # Training process
        all_loss = train_with_rectified_L2(model_XOR, loss_function, optimizer, X_train, y_train,
                                           no_of_epochs=params["epochs"],
                                           ALPHA=params["alpha"],
                                           LAMBDA=params["lambda"],
                                           initial_lr=params["initial_learning_rate"],
                                           max_lr=params["maximum_learning_rate"])

        # Log the final loss
        final_loss = all_loss[-1]
        mlflow.log_metric("final_loss", final_loss)

        # Determine and log convergence
        is_converged = final_loss < convergence_threshold
        mlflow.log_metric("converged", int(is_converged))

        # Log artifacts if needed (e.g., plots)
        # mlflow.log_artifact("path_to_your_artifact")

# Ensure the run ends when the script exits the loop
mlflow.end_run()

0.7704564332962036
0.2
0.7597321271896362
0.20002666666666669
0.7503941059112549
0.20005333333333333
0.7422833442687988
0.20008
0.7352540493011475
0.20010666666666668
0.7291741371154785
0.20013333333333336
0.7239246368408203
0.20016
0.719399094581604
0.20018666666666668
0.715502917766571
0.20021333333333335
0.7121527194976807
0.20024
0.70927494764328
0.20026666666666668
0.7068052887916565
0.20029333333333335
0.7046874165534973
0.20032
0.7028725147247314
0.20034666666666667
0.7013182044029236
0.20037333333333335
0.699987530708313
0.20040000000000002
0.6988489627838135
0.20042666666666667
0.6978750824928284
0.20045333333333334
0.6970421075820923
0.20048000000000002
0.6963301301002502
0.20050666666666667
0.6957212686538696
0.20053333333333334
0.6952008008956909
0.20056000000000002
0.6947558522224426
0.2005866666666667
0.6943756341934204
0.20061333333333334
0.6940504312515259
0.20064
0.6937722563743591
0.2006666666666667
0.6935343146324158
0.20069333333333333
0.6933307647705078
0.20072
0.6

KeyboardInterrupt: 